### ISSUE TITLE
Integration stopped working after upgrading to 2022.3.0

### ISSUE THREAD

**Issue by gui28347** [widewing/ha-toyota-na#30]
If upgrade to 2022.3.0 it make integration stop work.

Rolling it back to 2022.2.9 make it work agian.

Can you check please?

Thanks,

**Comment by Vault42x** [comment]
Can confirm.  Stopped working with update to 2022.3.0.

```
2022-03-02 20:33:47 ERROR (SyncWorker_0) [homeassistant.util.package] Unable to install package toyota-na==1.1.0: ERROR: Cannot install pyjwt[crypto]==2.1.0 because these package versions have conflicting dependencies.
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
2022-03-02 20:33:47 ERROR (MainThread) [homeassistant.setup] Setup failed for toyota_na: Requirements for toyota_na not found: ['toyota-na==1.1.0'].
```

**Comment by jlmaners** [comment]
This is fixed in the latest alpha release. We'll work to back-port the patch for that to the stable branch sometime over the next couple of days.

**Comment by antasp3136** [comment]
I have not been able to get this to work at all.. Not the Stable branch or the Alpha releases. I have two 2020 models. 1 tacoma and 1 4runner. The Tacoma is set as the primary car and has remote connect services enabled where I can start the car, lock and see mileage and fuel status. The 4runner does not have remote connect but I can still see mileage and fuel status. This would be really cool to get working in homeassistant.

**Comment by antasp3136** [comment]
This is my error. Would be great if the 4runner is the problem if i could just ignore that vehical and just pull in the data with the tacoma since it has the remote connect services.

Traceback (most recent call last):
  File "/config/custom_components/toyota_na/__init__.py", line 108, in update_vehicles_status
    raw_vehicles = await get_vehicles(client)
  File "/usr/local/lib/python3.9/site-packages/toyota_na/vehicle/vehicle.py", line 37, in get_vehicles
    await vehicle.update()
  File "/usr/local/lib/python3.9/site-packages/toyota_na/vehicle/vehicle_generations/seventeen_cy_plus.py", line 76, in update
    vehicle_status = await self._client.get_vehicle_status(self._vin)
  File "/usr/local/lib/python3.9/site-packages/toyota_na/client.py", line 67, in get_vehicle_status
    return await self.get_vehicle_status_17cyplus(vin)
  File "/usr/local/lib/python3.9/site-packages/toyota_na/client.py", line 80, in get_vehicle_status_17cyplus
    return await self.api_get("v1/global/remote/status", {"VIN": vin})
  File "/usr/local/lib/python3.9/site-packages/toyota_na/client.py", line 41, in api_get
    return await self.api_request("GET", endpoint, header_params)
  File "/usr/local/lib/python3.9/site-packages/toyota_na/client.py", line 31, in api_request
    resp.raise_for_status()
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1004, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 500, message='Internal Server Error', url=URL('https://oneapi.telematicsct.com/v1/global/remote/status')

**Comment by vanstinator** [comment]
This is now fixed in https://github.com/widewing/ha-toyota-na/releases/tag/v2.0.0
